[package]
name = "capture-runner"
version = "0.1.0"
authors = ["Zack Pierce <zachary.pierce@gmail.com>"]
edition = "2018"

[dependencies]
async-trait = "0.1.40"
cucumber_rust = { path = ".." }
futures = "0.3.5"
